// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrajaComigo.Data;

namespace TrajaComigo.Migrations
{
    [DbContext(typeof(TrajaComigoBD))]
    partial class TrajaComigoBDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrajaComigo.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Concelho")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TrajaComigo.Models.DetalhesEncomendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Encomenda")
                        .HasColumnType("int");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("PrecoUni")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("Produto")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Tamanhos")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("Encomenda");

                    b.HasIndex("Produto");

                    b.ToTable("DetalhesEncomendas");
                });

            modelBuilder.Entity("TrajaComigo.Models.Encomendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cliente")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<byte[]>("DataEncomenda")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("MoradaEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<decimal>("PrecoFinal")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("PrecoProduto")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("TipoPagamento")
                        .HasColumnType("Text")
                        .HasMaxLength(255);

                    b.Property<decimal>("ValorEntrega")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Cliente");

                    b.ToTable("Encomendas");
                });

            modelBuilder.Entity("TrajaComigo.Models.EstadoEncomendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("DataPrevisao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("Encomenda")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasColumnType("Text")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Encomenda");

                    b.ToTable("EstadoEncomendas");
                });

            modelBuilder.Entity("TrajaComigo.Models.Produtos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoUni")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("TrajaComigo.Models.DetalhesEncomendas", b =>
                {
                    b.HasOne("TrajaComigo.Models.Encomendas", "EncomendaId")
                        .WithMany()
                        .HasForeignKey("Encomenda");

                    b.HasOne("TrajaComigo.Models.Produtos", "ProdutoId")
                        .WithMany()
                        .HasForeignKey("Produto");
                });

            modelBuilder.Entity("TrajaComigo.Models.Encomendas", b =>
                {
                    b.HasOne("TrajaComigo.Models.Clientes", "ClienteId")
                        .WithMany()
                        .HasForeignKey("Cliente");
                });

            modelBuilder.Entity("TrajaComigo.Models.EstadoEncomendas", b =>
                {
                    b.HasOne("TrajaComigo.Models.Encomendas", "EncomendaId")
                        .WithMany()
                        .HasForeignKey("Encomenda");
                });
#pragma warning restore 612, 618
        }
    }
}
